### PR TITLE
Add java.lang.Math.*

### PR DESCRIPTION
**Pull request by chitoku-k**
Adds the following Math functions:
- Math.acos()
- Math.addExact()
- Math.asin()
- Math.atan()
- Math.atan2()
- Math.cbrt()
- Math.ceil()
- Math.copySign()
- Math.cos()
- Math.cosh()
- Math.exp()
- Math.expm1()
- Math.floor()
- ~~Math.floorDiv()~~
- ~~Math.floorMod()~~
- Math.incrementExact()
- Math.log()
- Math.log10()
- Math.log1p()
- Math.max()
- Math.min()
- ~~Math.multiplyExact()~~
- ~~Math.multiplyFull()~~
- Math.pow()
- Math.random()
- Math.round()
- Math.sin()
- Math.sinh()
- Math.sqrt()
- Math.subtractExact()
- Math.tan()
- Math.tanh()

### CODE REVIEW

**Comment by chitoku-k** [comment]
@memory-agape 
From JVM implementation, our `PrintStream` also has to accept `double` and `float`. What do you think?
https://github.com/php-java/java-io-package/blob/c646b97f25e227ef3939ba884a5d5e03a47333d2/src/java/io/PrintStream.php

**Comment by memory-agape** [comment]
@chitoku-k 
Yes, It is old implementation. 
So, there is a need to be fixed!

I will fix it later.

**Comment by memory-agape** [comment]
@chitoku-k 
Hi, chitoku-san!

I fixed it issues by https://github.com/php-java/java-io-package/pull/3 and https://github.com/php-java/php-java/pull/98
So, you can pass `double` and `float` values to PrintStream.
Please try it.

**Comment by chitoku-k** [comment]
@memory-agape 
That was so nice of you handled this issue! It seemed that some additional fixes automatically resolved this as well.

**Comment by memory-agape** [comment]
@chitoku-k 
Thanks!

**Pull request merged**
