### PR TITLE
Add java.lang.String#replace(CharSequence, CharSequence)

### PR DESCRIPTION
**Pull request by chitoku-k**

### CODE REVIEW

**Comment by memory-agape** [comment]
@chitoku-k 
Thanks! The method needs `CharSequence` parameters.
In this case, you need with wrapping  by the `CharSequence` class.

For example is here:

```php
    public function testReplace()
    {
        ob_start();
        $this->initiatedJavaClasses['ImitateJavaLangStringTest']
            ->getInvoker()
            ->getStatic()
            ->getMethods()
            ->call(
                'replace',
                'abcabc',
                new \PHPJava\Imitation\java\lang\CharSequence('b'),
                new \PHPJava\Imitation\java\lang\CharSequence('c')
            );
        $value = ob_get_clean();
        $this->assertEquals('accacc', $value);
    }
```

But, the `CharSequence` has not been implemented therefore you need to implement the `CharSequence` class previously.

Or, You can resolve if ambiguous options to enable (Not recommended).

```php
$javaClass = new JavaClass(
    new FileReader('Test'),
    [
        'validation' => [
            'method' => [
                'arguments_count_only' => true,
            ],
        ],
    ]
);
```

See: https://github.com/php-java/php-java#call-ambiguous-method-into-java-from-php

**Comment by chitoku-k** [comment]
I think `CharSequence` is not something that is going to be instantiated because it is an interface. Any thoughts?

**Comment by memory-agape** [comment]
@chitoku-k 
Okay, Its problem is resolved (https://github.com/php-java/php-java/pull/89).

Change as such as under:

- In \PHPJava\Imitation\java\lang\_String
```php
// use PHPJava\Imitation\java\io\Serializable;
// use PHPJava\Imitation\java\lang\CharSequence;
// use PHPJava\Imitation\java\util\Comparator;
// use PHPJava\Imitation\java\util\stream\IntStream;
```

to 

```
// use PHPJava\Imitation\java\io\Serializable;
use PHPJava\Imitation\java\lang\CharSequence;
// use PHPJava\Imitation\java\util\Comparator;
// use PHPJava\Imitation\java\util\stream\IntStream;
```

And, add `implements` after the extends

```php
class _String extends _Object implements CharSequence
```

I'm thinking of your code may work without changes.

**Comment by chitoku-k** [comment]
@memory-agape Looks like it's still failing 😢

**Comment by chitoku-k** [comment]
Rebased. (Please let me know if you don't like this flow of resolving conflicts.)

**Comment by memory-agape** [comment]
@chitoku-k 
PHPJava recognize  as the _Char if string is one character.
Therefore, I'm thinking that you need wrapping by the `_String`.

```php
$this->initiatedJavaClasses['ImitateJavaLangStringTest']
            ->getInvoker()
            ->getStatic()
            ->getMethods()
            ->call(
                'replace',
                'abcabc',
                new _String('b'),
                new _String('c')
            );
```

It works fine in my environment.

**Comment by chitoku-k** [comment]
@memory-agape 
Thanks for your advice, finally it passed!

**Comment by memory-agape** [comment]
@chitoku-k 
Thank you as always!

**Pull request merged**
