### PR TITLE
Add java.lang.String#charAt(int)

### PR DESCRIPTION
**Pull request by chitoku-k**

### CODE REVIEW

**Comment by memory-agape** [comment]
Great contribution!

**Comment by memory-agape** [comment]
@chitoku-k 
Test needs a promise for expected result.
For example test is here:
- https://github.com/php-java/java-lang-package/blob/master/tests/ImitateJavaLangMathTest.php

It check return value from executed method including parameters.

**Comment by chitoku-k** [comment]
@memory-agape 

Thanks for your comment. I've actually checked that test and what I wanted to know is that:
- How do I write tests?
- Where do I put them?

**Comment by memory-agape** [comment]
@chitoku-k 
Thanks. Okay, I answer your questions.

> How do I write tests?
> Where do I put them?

Progressing as follows:

- 1) Your need to put fixture (java testing file) into `tests/fixtures/java` directory.
  - It needs call a defined method by you.
  - For example:
if you defined method is `Math.decrementExact` then as following:
In Java (you need to put into `tests/fixtures/java`):
```java
    // You need to add prefix `test`
    public static void testDecrementExact(int a)
    {
        System.out.println(Math.decrementExact(a));
    }
```

In PHP (you need to put into `tests/` under.):
```
    protected $fixtures = [
        // To write fixture name that you defined java classes for tests.
        'ImitateJavaLangMathTest',
    ];

    public function testDecrementExact()
    {
        ob_start();
        // Call defined fixture
        $this->initiatedJavaClasses['ImitateJavaLangMathTest']
            ->getInvoker()
            ->getStatic()
            ->getMethods()
            ->call(
                // call defined method
                'decrementExact',
                // parameter
                1234
            );
        $value = (int) ob_get_clean();

        // Assert result
        $this->assertEquals(1233, $value);
    }
```

**Comment by chitoku-k** [comment]
@memory-agape 
Thank you! I'll try following your suggestions.

BTW, I am just thinking that this was not a good start for my contribution to this project because for now, it lacks of the implementation for the `Character` class and the actual type that `String#charAt(int)` returns is not `String` but `Character`. What do you think?

**Comment by memory-agape** [comment]
@chitoku-k 
It is exactly as you said. 
but,  We think to implement as much as possible because for java's package is huge amount.

**Comment by chitoku-k** [comment]
@memory-agape 
OK. So far I want to prioritize all these classes as to which one to implement first. And... probably, `Character` should be implemented earlier than `String` (despite `toString()`), shouldn't it?

**Comment by memory-agape** [comment]
I checked `https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#charAt(int)`

It wrote return values is:
```
public [char] charAt​(int index)
```

I think the method returns `char` type.
So, I think to resolve with wrap by `\PHPJava\Kernel\Types\_Char` class.
Could you try it?

**Comment by memory-agape** [comment]
@chitoku-k 
Wow! Amazing! 

Thanks!!!

You can merge the PR yourself!

**Pull request merged**
